# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import metric_service_pb2 as metric__service__pb2


class MetricServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendMetricAndWait = channel.unary_unary(
                '/metricservice.MetricService/SendMetricAndWait',
                request_serializer=metric__service__pb2.MetricRequest.SerializeToString,
                response_deserializer=metric__service__pb2.MetricResponse.FromString,
                )
        self.ResetRoundState = channel.unary_unary(
                '/metricservice.MetricService/ResetRoundState',
                request_serializer=metric__service__pb2.RoundRequest.SerializeToString,
                response_deserializer=metric__service__pb2.Empty.FromString,
                )


class MetricServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendMetricAndWait(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetRoundState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MetricServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendMetricAndWait': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMetricAndWait,
                    request_deserializer=metric__service__pb2.MetricRequest.FromString,
                    response_serializer=metric__service__pb2.MetricResponse.SerializeToString,
            ),
            'ResetRoundState': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetRoundState,
                    request_deserializer=metric__service__pb2.RoundRequest.FromString,
                    response_serializer=metric__service__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'metricservice.MetricService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MetricService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendMetricAndWait(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/metricservice.MetricService/SendMetricAndWait',
            metric__service__pb2.MetricRequest.SerializeToString,
            metric__service__pb2.MetricResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ResetRoundState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/metricservice.MetricService/ResetRoundState',
            metric__service__pb2.RoundRequest.SerializeToString,
            metric__service__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
