# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: metric_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14metric_service.proto\x12\rmetricservice\" \n\rMetricRequest\x12\x0f\n\x07l2_norm\x18\x01 \x01(\x02\"\x1d\n\x0cRoundRequest\x12\r\n\x05round\x18\x01 \x01(\x05\"$\n\x0eMetricResponse\x12\x12\n\nstop_round\x18\x01 \x01(\x08\"\x07\n\x05\x45mpty2\xab\x01\n\rMetricService\x12R\n\x11SendMetricAndWait\x12\x1c.metricservice.MetricRequest\x1a\x1d.metricservice.MetricResponse\"\x00\x12\x46\n\x0fResetRoundState\x12\x1b.metricservice.RoundRequest\x1a\x14.metricservice.Empty\"\x00\x62\x06proto3')



_METRICREQUEST = DESCRIPTOR.message_types_by_name['MetricRequest']
_ROUNDREQUEST = DESCRIPTOR.message_types_by_name['RoundRequest']
_METRICRESPONSE = DESCRIPTOR.message_types_by_name['MetricResponse']
_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
MetricRequest = _reflection.GeneratedProtocolMessageType('MetricRequest', (_message.Message,), {
  'DESCRIPTOR' : _METRICREQUEST,
  '__module__' : 'metric_service_pb2'
  # @@protoc_insertion_point(class_scope:metricservice.MetricRequest)
  })
_sym_db.RegisterMessage(MetricRequest)

RoundRequest = _reflection.GeneratedProtocolMessageType('RoundRequest', (_message.Message,), {
  'DESCRIPTOR' : _ROUNDREQUEST,
  '__module__' : 'metric_service_pb2'
  # @@protoc_insertion_point(class_scope:metricservice.RoundRequest)
  })
_sym_db.RegisterMessage(RoundRequest)

MetricResponse = _reflection.GeneratedProtocolMessageType('MetricResponse', (_message.Message,), {
  'DESCRIPTOR' : _METRICRESPONSE,
  '__module__' : 'metric_service_pb2'
  # @@protoc_insertion_point(class_scope:metricservice.MetricResponse)
  })
_sym_db.RegisterMessage(MetricResponse)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'metric_service_pb2'
  # @@protoc_insertion_point(class_scope:metricservice.Empty)
  })
_sym_db.RegisterMessage(Empty)

_METRICSERVICE = DESCRIPTOR.services_by_name['MetricService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _METRICREQUEST._serialized_start=39
  _METRICREQUEST._serialized_end=71
  _ROUNDREQUEST._serialized_start=73
  _ROUNDREQUEST._serialized_end=102
  _METRICRESPONSE._serialized_start=104
  _METRICRESPONSE._serialized_end=140
  _EMPTY._serialized_start=142
  _EMPTY._serialized_end=149
  _METRICSERVICE._serialized_start=152
  _METRICSERVICE._serialized_end=323
# @@protoc_insertion_point(module_scope)
